### ISSUE TITLE
[Bug]: model.get_machines() doesn't properly update its result when iterate through a list of models

### ISSUE THREAD

**Issue by agileshaw** [juju/python-libjuju#769] opened 2022-11-15 16:38 UTC
### Description

When iterate through a list of models and connecting to them one at a time, if a previous model has more machines than the current one, [model.get_machines()](https://github.com/juju/python-libjuju/blob/fd89d1a0bb4f162969b3c479cb4701c501cc6786/juju/model.py#L2217) would return the list of machines in the previous model instead of the current. It seems that the result data is not properly "refreshed". 

Such an issue doesn't seem to occur if the numbers of machines in each model are in ascending order. 

The log of a simple test run showing the bug can be found [here](https://pastebin.ubuntu.com/p/PNm69R7jRP/). 

### Urgency

Blocker for our release

### Python-libjuju version

2.9.11, 3.0.0, 3.0.4

### Juju version

2.9.37

### Reproduce / Test

```python
from juju.model import Model
import asyncio

async def juju_stats():
    model = Model()
    for name in ["default", "controller"]: # assuming default model has more machines than controller model
        await model.connect(name)
        print(await model.get_machines())
        await model.disconnect()

asyncio.run(juju_stats())
```

**Comment by juanmanuel-tirado** [comment] 2022-11-16 09:28
Yes, you're right this is an issue regarding the reuse of the connections and the objects. Meanwhile, you can skip this problem creating a new `model` for every connection. Something like:

```python
from juju.model import Model
import asyncio

async def juju_stats():
    for name in ["default", "controller"]: # assuming default model has more machines than controller model
        model = Model()
        await model.connect(name)
        print(await model.get_machines())
        await model.disconnect()

asyncio.run(juju_stats())
```
We are aware that this is a workaround and not the expected behaviour. Because there is a solution for this, I will close this issue. Feel free to reopen it if the problem persists.

**Closed by juanmanuel-tirado** 2022-11-16 09:28 UTC
Labels: bug
