### ISSUE TITLE
Failed deploying a local bundle with a charm pointing to CharmHub

### ISSUE THREAD

**Issue by davigar15** [juju/python-libjuju#521] opened 2021-08-19 12:50 UTC
I am getting this error when deploying a local bundle that looks like this with libjuju

```yaml
description: Squid Bundle
bundle: kubernetes
applications:
  hello-kubecon:
    charm: 'ch:hello-kubecon'
    scale: 1
```

Getting this error:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/n2vc/libjuju.py", line 561, in deploy
    await model.deploy(uri)
  File "/usr/local/lib/python3.6/dist-packages/juju/model.py", line 1445, in deploy
    await handler.execute_plan()
  File "/usr/local/lib/python3.6/dist-packages/juju/bundle.py", line 169, in execute_plan
    self.references[step.id_] = await change.run(self)
  File "/usr/local/lib/python3.6/dist-packages/juju/bundle.py", line 439, in run
    entity_id = await context.charmstore.entityId(self.charm, channel=self.channel)
  File "/usr/local/lib/python3.6/dist-packages/juju/charmstore.py", line 30, in coro
    return await self.loop.run_in_executor(None, method)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/theblues/charmstore.py", line 337, in entityId
    data = self._get(_add_channel(url, channel))
  File "/usr/local/lib/python3.6/dist-packages/theblues/charmstore.py", line 82, in _get
    raise EntityNotFound(url)
theblues.errors.EntityNotFound: https://api.jujucharms.com/charmstore/v5/ch:hello-kubecon/meta/any
```

**Comment by davigar15** [comment] 2021-08-19 13:00
How to reproduce:

```python
"""
This example:

1. Connects to the current model
2. Deploy a charm from charmhub and waits until it reports itself active
3. Destroys the unit and application

"""
from juju import loop
from juju.model import Model


async def main():
    model = Model()
    print('Connecting to model')
    # connect to current model with current user, per Juju CLI
    await model.connect()

    try:
        print('Deploying hello-kubecon')
        application = await model.deploy(
            'ch:hello-kubecon-10',
            application_name='test',
            series='kubernetes',
            channel='stable',
        )

        print('Waiting for active')
        await model.block_until(
            lambda: all(unit.workload_status == 'active'
                        for unit in application.units))

        print('Removing ubuntu')
        await application.remove()
    finally:
        print('Disconnecting from model')
        await model.disconnect()


if __name__ == '__main__':
    loop.run(main())

```

**Comment by SimonRichardson** [comment] 2021-08-19 13:32
Duplicate of https://github.com/juju/python-libjuju/issues/511

**Closed by SimonRichardson** 2021-08-19 13:32 UTC
