### ISSUE TITLE
[Bug]: python-libjuju can't connect to a model with controller version 3.0-rc2

### ISSUE THREAD

**Issue by gabrielcocenza** [juju/python-libjuju#748] opened 2022-10-19 19:39 UTC
### Description

[bug/1993334](https://bugs.launchpad.net/juju/+bug/1993334) shows that juju-lint is failing because it's not able to connect to a model. Steps to reproduce it:

- Bootstrap lxd with juju 3.0-rc2
- juju add-model test
- pip3 install juju
- run the python script as showed bellow in `Reproduce / Test`

[Logs](https://pastebin.canonical.com/p/tTVKVcsCfx/) of the error

This problem **doesn't** happen on juju version `2.9.33`

### Urgency

Blocker for our release

### Python-libjuju version

3.0.2

### Juju version

3.0-rc2

### Reproduce / Test

```python
python3 -m asyncio

from juju.model import Model
model = Model()
await model.connect_current()
```

**Comment by cderici** [comment] 2022-10-20 14:16
The error in the logs is fixed by https://github.com/juju/python-libjuju/pull/745, and I'm currently unable to reproduce this with the current head. So it should be fixed in the next release (coming in 1-2 days).

**Comment by cderici** [comment] 2022-10-20 14:17
Feel free to reopen this if the problem persists on your end after the update :+1:

**Closed by cderici** 2022-10-20 14:16 UTC
Labels: bug
