### ISSUE TITLE
cannot "upgrade" a bundle by deploying twice

### ISSUE THREAD

**Issue by davigar15** [juju/python-libjuju#362] opened 2019-10-21 11:34 UTC
Hello,

Currently, I can't upgrade an application in libjuju. With the juju client, you can do the following:
```bash
juju deploy <charm|bundle>
juju deploy <charm|bundle> # Upgraded, with new revision numbers
```

But with libjuju, when I deploy a bundle or a charm, that has already been deployed, I'm getting an error saying that the application already exists.

The expected result I think it should be to upgrade the charm if the revision has changed, and if it doesn't then do nothing, but don't give an error.

I have used k8s charms to to the test, but I think it may affect all kind of charms. This is the code I've used:
```python3
from juju import loop
from juju.model import Model
from pathlib import Path
import logging


async def main():
    model = Model()
    print('Connecting to model')
    # Connect to current model with current user, per Juju CLI
    await model.connect()

    try:
        print('Deploying')
        apps = await model.deploy( 'cs:~omnivector/redis-k8s-2' )

        print("Successfully deployed!")
        # application = model.applications['redis-k8s']
        
        print("Upgrading")
        apps = await model.deploy( 'cs:~omnivector/redis-k8s-3' )
        print('Removing')
    finally:
        print('Disconnecting from model')
        await model.disconnect()
        print("Success")


if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    ws_logger = logging.getLogger('websockets.protocol')
    ws_logger.setLevel(logging.INFO)
    loop.run(main())
```

Full log
```
(venv) davigar15@Canonical:~/code/python-libjuju$ python3 examples/deploy_and_upgrade_k8s.py 
DEBUG:asyncio:Using selector: EpollSelector
Connecting to model
DEBUG:juju.client.connection:Driver connected to juju wss://10.152.183.114:17070/model/eb5d7991-619a-4bb0-8cb8-2087ddc3478e/api
DEBUG:juju.client.connection:connection 140273791615496 -> {
  "type": "Admin",
  "request": "Login",
  "version": 3,
  "params": {
    "auth-tag": "user-admin",
    "credentials": "c73fdec25704b4c0c23da2260bcc4d14"
  },
  "request-id": 1
}
DEBUG:juju.client.connection:connection 140273791615496 <- {'request-id': 1, 'response': {'servers': [[{'value': '10.152.183.114', 'type': 'ipv4', 'scope': 'local-cloud', 'port': 17070}]], 'model-tag': 'model-eb5d7991-619a-4bb0-8cb8-2087ddc3478e', 'controller-tag': 'controller-0a672e62-9e0f-43a2-82dd-b4aced4b0080', 'user-info': {'display-name': '', 'identity': 'user-admin', 'controller-access': 'superuser', 'model-access': 'admin'}, 'facades': [{'name': 'Action', 'versions': [2, 3]}, {'name': 'ActionPruner', 'versions': [1]}, {'name': 'Agent', 'versions': [2]}, {'name': 'AgentTools', 'versions': [1]}, {'name': 'AllWatcher', 'versions': [1]}, {'name': 'Annotations', 'versions': [2]}, {'name': 'Application', 'versions': [1, 2, 3, 4, 5, 6, 7, 8, 9]}, {'name': 'ApplicationScaler', 'versions': [1]}, {'name': 'Backups', 'versions': [1, 2]}, {'name': 'Block', 'versions': [2]}, {'name': 'Bundle', 'versions': [1, 2, 3]}, {'name': 'CAASAgent', 'versions': [1]}, {'name': 'CAASFirewaller', 'versions': [1]}, {'name': 'CAASOperator', 'versions': [1]}, {'name': 'CAASOperatorProvisioner', 'versions': [1]}, {'name': 'CAASOperatorUpgrader', 'versions': [1]}, {'name': 'CAASUnitProvisioner', 'versions': [1]}, {'name': 'CharmRevisionUpdater', 'versions': [2]}, {'name': 'Charms', 'versions': [2]}, {'name': 'Cleaner', 'versions': [2]}, {'name': 'Client', 'versions': [1, 2]}, {'name': 'CredentialManager', 'versions': [1]}, {'name': 'CredentialValidator', 'versions': [1, 2]}, {'name': 'CrossModelRelations', 'versions': [1]}, {'name': 'Deployer', 'versions': [1]}, {'name': 'DiskManager', 'versions': [2]}, {'name': 'EntityWatcher', 'versions': [2]}, {'name': 'ExternalControllerUpdater', 'versions': [1]}, {'name': 'FanConfigurer', 'versions': [1]}, {'name': 'FilesystemAttachmentsWatcher', 'versions': [2]}, {'name': 'FirewallRules', 'versions': [1]}, {'name': 'Firewaller', 'versions': [3, 4, 5]}, {'name': 'HighAvailability', 'versions': [2]}, {'name': 'HostKeyReporter', 'versions': [1]}, {'name': 'ImageManager', 'versions': [2]}, {'name': 'ImageMetadata', 'versions': [3]}, {'name': 'InstanceMutater', 'versions': [1, 2]}, {'name': 'InstancePoller', 'versions': [3]}, {'name': 'KeyManager', 'versions': [1]}, {'name': 'KeyUpdater', 'versions': [1]}, {'name': 'LeadershipService', 'versions': [2]}, {'name': 'LifeFlag', 'versions': [1]}, {'name': 'LogForwarding', 'versions': [1]}, {'name': 'Logger', 'versions': [1]}, {'name': 'MachineActions', 'versions': [1]}, {'name': 'MachineManager', 'versions': [2, 3, 4, 5, 6]}, {'name': 'MachineUndertaker', 'versions': [1]}, {'name': 'Machiner', 'versions': [1]}, {'name': 'MeterStatus', 'versions': [1]}, {'name': 'MetricsAdder', 'versions': [2]}, {'name': 'MetricsDebug', 'versions': [2]}, {'name': 'MetricsManager', 'versions': [1]}, {'name': 'MigrationFlag', 'versions': [1]}, {'name': 'MigrationMaster', 'versions': [1]}, {'name': 'MigrationMinion', 'versions': [1]}, {'name': 'MigrationStatusWatcher', 'versions': [1]}, {'name': 'ModelConfig', 'versions': [1, 2]}, {'name': 'ModelGeneration', 'versions': [1, 2]}, {'name': 'ModelUpgrader', 'versions': [1]}, {'name': 'NotifyWatcher', 'versions': [1]}, {'name': 'OfferStatusWatcher', 'versions': [1]}, {'name': 'Payloads', 'versions': [1]}, {'name': 'PayloadsHookContext', 'versions': [1]}, {'name': 'Pinger', 'versions': [1]}, {'name': 'Provisioner', 'versions': [3, 4, 5, 6, 7, 8, 9]}, {'name': 'ProxyUpdater', 'versions': [1, 2]}, {'name': 'Reboot', 'versions': [2]}, {'name': 'RelationStatusWatcher', 'versions': [1]}, {'name': 'RelationUnitsWatcher', 'versions': [1]}, {'name': 'RemoteRelations', 'versions': [1]}, {'name': 'Resources', 'versions': [1]}, {'name': 'ResourcesHookContext', 'versions': [1]}, {'name': 'Resumer', 'versions': [2]}, {'name': 'RetryStrategy', 'versions': [1]}, {'name': 'SSHClient', 'versions': [1, 2]}, {'name': 'Singular', 'versions': [2]}, {'name': 'Spaces', 'versions': [2, 3]}, {'name': 'StatusHistory', 'versions': [2]}, {'name': 'Storage', 'versions': [3, 4, 5, 6]}, {'name': 'StorageProvisioner', 'versions': [3, 4]}, {'name': 'StringsWatcher', 'versions': [1]}, {'name': 'Subnets', 'versions': [2]}, {'name': 'Undertaker', 'versions': [1]}, {'name': 'UnitAssigner', 'versions': [1]}, {'name': 'Uniter', 'versions': [4, 5, 6, 7, 8, 9, 10, 11, 12]}, {'name': 'UpgradeSeries', 'versions': [1]}, {'name': 'UpgradeSteps', 'versions': [1]}, {'name': 'Upgrader', 'versions': [1]}, {'name': 'VolumeAttachmentPlansWatcher', 'versions': [1]}, {'name': 'VolumeAttachmentsWatcher', 'versions': [2]}], 'server-version': '2.6.10'}}
DEBUG:juju.model:Starting watcher task
DEBUG:juju.client.connection:connection 140273791615496 -> {
  "type": "Pinger",
  "request": "Ping",
  "version": 1,
  "params": {},
  "request-id": 2
}
DEBUG:juju.client.connection:connection 140273791615496 -> {
  "type": "Client",
  "request": "WatchAll",
  "version": 2,
  "params": {},
  "request-id": 3
}
DEBUG:juju.client.connection:connection 140273791615496 <- {'request-id': 2, 'response': {}}
DEBUG:juju.client.connection:connection 140273791615496 <- {'request-id': 3, 'response': {'watcher-id': '1'}}
DEBUG:juju.client.connection:connection 140273791615496 -> {
  "type": "AllWatcher",
  "request": "Next",
  "version": 1,
  "params": {},
  "Id": "1",
  "request-id": 4
}
DEBUG:juju.client.connection:connection 140273791615496 <- {'request-id': 4, 'response': {'deltas': [['charm', 'change', {'model-uuid': 'eb5d7991-619a-4bb0-8cb8-2087ddc3478e', 'charm-url': 'cs:~omnivector/redis-k8s-3', 'charm-version': '3a0a7e4-dirty', 'life': 'alive', 'profile': None}]]}}
DEBUG:juju.model:unknown delta type: charm
DEBUG:juju.client.connection:connection 140273791615496 -> {
  "type": "Client",
  "request": "ModelInfo",
  "version": 2,
  "params": {},
  "request-id": 5
}
DEBUG:juju.client.connection:connection 140273791615496 -> {
  "type": "AllWatcher",
  "request": "Next",
  "version": 1,
  "params": {},
  "Id": "1",
  "request-id": 6
}
DEBUG:juju.client.connection:connection 140273791615496 <- {'request-id': 5, 'response': {'name': 'testing', 'type': 'caas', 'uuid': 'eb5d7991-619a-4bb0-8cb8-2087ddc3478e', 'controller-uuid': 'controller-0a672e62-9e0f-43a2-82dd-b4aced4b0080', 'is-controller': False, 'provider-type': 'kubernetes', 'default-series': 'bionic', 'cloud-tag': 'cloud-microk8s', 'cloud-region': 'localhost', 'cloud-credential-tag': 'cloudcred-microk8s_admin_microk8s', 'owner-tag': 'user-admin', 'life': 'alive', 'status': {'status': '', 'info': '', 'since': None}, 'users': None, 'machines': None, 'sla': {'level': 'unsupported', 'owner': ''}, 'agent-version': '2.6.10'}}
DEBUG:juju.model:Got ModelInfo: {'agent_version': <Number major=2 minor=6 patch=10 tag= build=0>, 'cloud_credential_tag': 'cloudcred-microk8s_admin_microk8s', 'cloud_region': 'localhost', 'cloud_tag': 'cloud-microk8s', 'controller_uuid': 'controller-0a672e62-9e0f-43a2-82dd-b4aced4b0080', 'default_series': 'bionic', 'is_controller': False, 'life': 'alive', 'machines': [], 'migration': None, 'name': 'testing', 'owner_tag': 'user-admin', 'provider_type': 'kubernetes', 'sla': <class 'juju.client._definitions.ModelSLAInfo'>({'level': 'unsupported', 'owner': '', 'unknown_fields': {}}), 'status': <class 'juju.client._definitions.EntityStatus'>({'data': None, 'info': '', 'since': None, 'status': '', 'unknown_fields': {}}), 'type_': 'caas', 'users': [], 'uuid': 'eb5d7991-619a-4bb0-8cb8-2087ddc3478e', 'unknown_fields': {}}
Deploying
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jujucharms.com:443
DEBUG:urllib3.connectionpool:https://api.jujucharms.com:443 "GET /charmstore/v5/~omnivector/redis-k8s-2/meta/any?include=bundle-machine-count&include=bundle-metadata&include=bundle-unit-count&include=charm-actions&include=charm-config&include=charm-metadata&include=common-info&include=extra-info&include=owner&include=published&include=resources&include=supported-series&include=terms HTTP/1.1" 200 698
DEBUG:juju.client.connection:connection 140273791615496 -> {
  "type": "Client",
  "request": "AddCharm",
  "version": 2,
  "params": {
    "channel": null,
    "force": false,
    "url": "cs:~omnivector/redis-k8s-2"
  },
  "request-id": 7
}
DEBUG:juju.client.connection:connection 140273791615496 <- {'request-id': 7, 'response': {}}
DEBUG:juju.client.connection:connection 140273791615496 -> {
  "type": "Resources",
  "request": "AddPendingResources",
  "version": 1,
  "params": {
    "tag": "application-redis-k8s",
    "url": "cs:~omnivector/redis-k8s-2",
    "resources": [
      {
        "description": "Redis docker image.",
        "fingerprint": null,
        "name": "redis_image",
        "origin": "store",
        "path": "",
        "revision": 0,
        "size": 0,
        "type": "oci-image"
      }
    ]
  },
  "request-id": 8
}
DEBUG:juju.client.connection:connection 140273791615496 <- {'request-id': 8, 'response': {'pending-ids': ['84ecc9c0-6d50-42e0-8b8e-36f6110a6287']}}
INFO:juju.model:Deploying cs:~omnivector/redis-k8s-2
DEBUG:juju.client.connection:connection 140273791615496 -> {
  "type": "Application",
  "request": "Deploy",
  "version": 8,
  "params": {
    "applications": [
      {
        "application": "redis-k8s",
        "channel": null,
        "charm-url": "cs:~omnivector/redis-k8s-2",
        "config": null,
        "config-yaml": "redis-k8s: {}\n",
        "constraints": null,
        "endpoint-bindings": null,
        "num-units": 1,
        "placement": [],
        "resources": {
          "redis_image": "84ecc9c0-6d50-42e0-8b8e-36f6110a6287"
        },
        "series": "kubernetes",
        "storage": null
      }
    ]
  },
  "request-id": 9
}
DEBUG:juju.client.connection:connection 140273791615496 <- {'request-id': 9, 'response': {'results': [{}]}}
DEBUG:juju.client.connection:connection 140273791615496 <- {'request-id': 6, 'response': {'deltas': [['charm', 'change', {'model-uuid': 'eb5d7991-619a-4bb0-8cb8-2087ddc3478e', 'charm-url': 'cs:~omnivector/redis-k8s-2', 'charm-version': '3a0a7e4-dirty', 'life': 'alive', 'profile': None}]]}}
DEBUG:juju.model:unknown delta type: charm
DEBUG:juju.client.connection:connection 140273791615496 -> {
  "type": "AllWatcher",
  "request": "Next",
  "version": 1,
  "params": {},
  "Id": "1",
  "request-id": 10
}
DEBUG:juju.client.connection:connection 140273791615496 <- {'request-id': 10, 'response': {'deltas': [['unit', 'change', {'model-uuid': 'eb5d7991-619a-4bb0-8cb8-2087ddc3478e', 'name': 'redis-k8s/1', 'application': 'redis-k8s', 'series': 'kubernetes', 'charm-url': '', 'life': 'alive', 'public-address': '', 'private-address': '', 'machine-id': '', 'ports': [], 'port-ranges': [], 'principal': '', 'subordinate': False, 'workload-status': {'current': 'waiting', 'message': 'agent initializing', 'since': '2019-10-21T11:27:31.782260223Z', 'version': ''}, 'agent-status': {'current': 'allocating', 'message': '', 'since': '2019-10-21T11:27:31.782260223Z', 'version': ''}}], ['application', 'change', {'model-uuid': 'eb5d7991-619a-4bb0-8cb8-2087ddc3478e', 'name': 'redis-k8s', 'exposed': False, 'charm-url': 'cs:~omnivector/redis-k8s-2', 'owner-tag': '', 'life': 'alive', 'min-units': 0, 'constraints': {}, 'subordinate': False, 'status': {'current': 'waiting', 'message': 'waiting for container', 'since': '2019-10-21T11:27:31.77325728Z', 'version': ''}, 'workload-version': ''}]]}}
DEBUG:juju.model:Model changed: unit add redis-k8s/1
DEBUG:juju.model:Model changed: application add redis-k8s
DEBUG:juju.client.connection:connection 140273791615496 -> {
  "type": "AllWatcher",
  "request": "Next",
  "version": 1,
  "params": {},
  "Id": "1",
  "request-id": 11
}
Successfully deployed!
Upgrading
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jujucharms.com:443
DEBUG:juju.client.connection:connection 140273791615496 <- {'request-id': 11, 'response': {'deltas': [['application', 'change', {'model-uuid': 'eb5d7991-619a-4bb0-8cb8-2087ddc3478e', 'name': 'redis-k8s', 'exposed': False, 'charm-url': 'cs:~omnivector/redis-k8s-2', 'owner-tag': '', 'life': 'alive', 'min-units': 0, 'constraints': {}, 'subordinate': False, 'status': {'current': 'waiting', 'message': 'agent initializing', 'since': '2019-10-21T11:27:31.782260223Z', 'version': ''}, 'workload-version': ''}]]}}
DEBUG:juju.model:Model changed: application change redis-k8s
DEBUG:juju.client.connection:connection 140273791615496 -> {
  "type": "AllWatcher",
  "request": "Next",
  "version": 1,
  "params": {},
  "Id": "1",
  "request-id": 12
}
DEBUG:urllib3.connectionpool:https://api.jujucharms.com:443 "GET /charmstore/v5/~omnivector/redis-k8s-3/meta/any?include=bundle-machine-count&include=bundle-metadata&include=bundle-unit-count&include=charm-actions&include=charm-config&include=charm-metadata&include=common-info&include=extra-info&include=owner&include=published&include=resources&include=supported-series&include=terms HTTP/1.1" 200 701
DEBUG:juju.client.connection:connection 140273791615496 -> {
  "type": "Client",
  "request": "AddCharm",
  "version": 2,
  "params": {
    "channel": null,
    "force": false,
    "url": "cs:~omnivector/redis-k8s-3"
  },
  "request-id": 13
}
DEBUG:juju.client.connection:connection 140273791615496 <- {'request-id': 13, 'response': {}}
DEBUG:juju.client.connection:connection 140273791615496 -> {
  "type": "Resources",
  "request": "AddPendingResources",
  "version": 1,
  "params": {
    "tag": "application-redis-k8s",
    "url": "cs:~omnivector/redis-k8s-3",
    "resources": [
      {
        "description": "Redis docker image.",
        "fingerprint": null,
        "name": "redis_image",
        "origin": "store",
        "path": "",
        "revision": 0,
        "size": 0,
        "type": "oci-image"
      }
    ]
  },
  "request-id": 14
}
DEBUG:juju.client.connection:connection 140273791615496 <- {'request-id': 14, 'response': {'pending-ids': ['a14af6a7-1cf2-4c11-8f4a-da78a775cd2d']}}
INFO:juju.model:Deploying cs:~omnivector/redis-k8s-3
DEBUG:juju.client.connection:connection 140273791615496 -> {
  "type": "Application",
  "request": "Deploy",
  "version": 8,
  "params": {
    "applications": [
      {
        "application": "redis-k8s",
        "channel": null,
        "charm-url": "cs:~omnivector/redis-k8s-3",
        "config": null,
        "config-yaml": "redis-k8s: {}\n",
        "constraints": null,
        "endpoint-bindings": null,
        "num-units": 1,
        "placement": [],
        "resources": {
          "redis_image": "a14af6a7-1cf2-4c11-8f4a-da78a775cd2d"
        },
        "series": "kubernetes",
        "storage": null
      }
    ]
  },
  "request-id": 15
}
DEBUG:juju.client.connection:connection 140273791615496 <- {'request-id': 15, 'response': {'results': [{'error': {'message': 'cannot add application "redis-k8s": application already exists', 'code': ''}}]}}
Disconnecting from model
DEBUG:juju.model:Stopping watcher task
DEBUG:juju.client.connection:connection 140273791615496 -> {
  "type": "AllWatcher",
  "request": "Stop",
  "version": 1,
  "params": {},
  "Id": "1",
  "request-id": 16
}
DEBUG:juju.client.connection:connection 140273791615496 <- {'request-id': 16, 'response': {}}
DEBUG:juju.model:Closing model connection
DEBUG:connector:Closing model connection
Success
Traceback (most recent call last):
  File "examples/deploy_and_upgrade_k8s.py", line 41, in <module>
    loop.run(main())
  File "/home/davigar15/code/python-libjuju/juju/loop.py", line 38, in run
    raise task.exception()
  File "examples/deploy_and_upgrade_k8s.py", line 29, in main
    apps = await model.deploy( 'cs:~omnivector/redis-k8s-3' )
  File "/home/davigar15/code/python-libjuju/juju/model.py", line 1431, in deploy
    devices=devices,
  File "/home/davigar15/code/python-libjuju/juju/model.py", line 1508, in _deploy
    result = await app_facade.Deploy(applications=[app])
  File "/home/davigar15/code/python-libjuju/juju/client/facade.py", line 472, in wrapper
    reply = await f(*args, **kwargs)
  File "/home/davigar15/code/python-libjuju/juju/client/_client8.py", line 784, in Deploy
    reply = await self.rpc(msg)
  File "/home/davigar15/code/python-libjuju/juju/client/facade.py", line 608, in rpc
    result = await self.connection.rpc(msg, encoder=TypeEncoder)
  File "/home/davigar15/code/python-libjuju/juju/client/connection.py", line 472, in rpc
    raise errors.JujuError(err_results)
juju.errors.JujuError: ['cannot add application "redis-k8s": application already exists']
```

Thanks

**Comment by SimonRichardson** [comment] 2019-11-04 18:00
I've started working on this for bundles - #364 

Note: you shouldn't be able to do `juju deploy <charm> and juju deploy <charm>`, as this will report an error stating that you've already deployed that application. Deploying a bundle is different and will upgrade a bundle to the latest version. Semantically they're a different beast.

**Comment by mitechie** [comment] 2019-11-04 18:17
Looking at this I'm very confused. I thought the issue was that there wasn't proper upgrade-charm support in pylibjuju but there is. However, the example code is trying to run "deploy" twice, which will fail. 

If you want to upgrade a charm you need to use the upgrade-charm path. 

Is there some reason that's not feasible here?

**Comment by AdamIsrael** [comment] 2019-11-04 18:30
@mitechie We're attempting to upgrade a bundle, which isn't currently supported via libjuju. You're absolutely right re upgrading a single charm.

Via the CLI, we can `juju deploy cs:bundle-0` and upgrade via `juju deploy cs:bundle-1`. That's the feature we're aiming to have implemented.

**Comment by mitechie** [comment] 2019-11-04 18:59
I spoke with Adam about this and how the "run a bundle deploy twice" isn't really a supported "ugprade" stategy. It's mainly there for dealing with potential failures in a large bundle and to help prevent needing to tear down and redeploy entirely. The issue is that upgrades are complicated and can present questions that Juju would need to know how to solve in differences in the model vs the bundle expectations. Upgrades should be handled more manually across a model (and thus be able to leverage things like actions, selecting the upgrade process/rollout strategy, etc) and there might be room in the future for extending the juju branches work (currently in 2.7 behind a feature flag) to advance the idea of upgrades to a model using the diff of commits to form a delta that can be applied cleanly. 

For now going to say this is a won't fix. If I'm not understanding the problem or there's other issues please feel free to reopen and we can discuss how we can enable you to move your work forward.

**Closed by mitechie** 2019-11-04 18:59 UTC
