### ISSUE TITLE
Error deploying bundle in K8s model

### ISSUE THREAD

**Issue by johnsca** [juju/python-libjuju#506] opened 2021-06-04 13:30 UTC
Got the following when trying to deploy a bundle with metadata v2 container charms (series set to `kubernetes`):

```
Traceback (most recent call last):
  File "tests/integration/test_charm.py", line 36, in test_build_and_deploy
    await ops_test.model.deploy(
  File ".tox/integration/lib/python3.8/site-packages/juju/model.py", line 1446, in deploy
    await handler.execute_plan()
  File ".tox/integration/lib/python3.8/site-packages/juju/bundle.py", line 167, in execute_plan
    self.references[step.id_] = await change.run(self)
  File ".tox/integration/lib/python3.8/site-packages/juju/bundle.py", line 660, in run
    return await context.model.applications[application].add_unit(
  File ".tox/integration/lib/python3.8/site-packages/juju/application.py", line 138, in add_unit
    result = await app_facade.AddUnits(
  File ".tox/integration/lib/python3.8/site-packages/juju/client/facade.py", line 480, in wrapper
    reply = await f(*args, **kwargs)
  File ".tox/integration/lib/python3.8/site-packages/juju/client/_client13.py", line 984, in AddUnits
    reply = await self.rpc(msg)
  File ".tox/integration/lib/python3.8/site-packages/juju/client/facade.py", line 623, in rpc
    result = await self.connection.rpc(msg, encoder=TypeEncoder)
  File ".tox/integration/lib/python3.8/site-packages/juju/client/connection.py", line 495, in rpc
    raise errors.JujuAPIError(result)
juju.errors.JujuAPIError: adding units to a container-based model not supported
```

Does `Application.add_unit()` need to unconditionally switch to [`ApplicationFacade.ScaleApplications()`](https://github.com/juju/python-libjuju/blob/eed19e4d8af20a29104e9a9bb50a960b1e49b0f9/juju/client/_client13.py#L1498) instead of `ApplicationFacade.AddUnits()`, or does it need to conditionally use that only on container type models (or something else entirely that I'm missing)?

**Comment by SimonRichardson** [comment] 2021-12-06 20:55
Yeah this is a bug in pylibjuju, essentially we should use scale instead of add unit only if the bundle is a k8s bundle. This is what Juju does internally.

@cderici can you look at this one.

**Comment by cderici** [comment] 2021-12-09 19:00
I'm a little confused here. This issue might not be valid anymore. If you're deploying a k8s bundle you shouldn't get an `AddUnitChange` in the first place. If a k8s bundle is trying to scale an app, then the plan should have `ScaleChange` instead. Otherwise the issue's on Juju's side.

Or, I am missing a use case here, in which case it'd help if someone points out a way to reproduce this problem.

**Comment by SimonRichardson** [comment] 2021-12-09 19:38
I believe this bundle.yaml with v2 charms. It might be worth asking @hmlanigan to verify this one.

**Comment by cderici** [comment] 2021-12-13 23:46
I suspect the issue is that the bundle in question has `series: kubernetes` line, instead of a `bundle: kubernetes`. For instance, take the following bundle (that deploys a local v2 charm -- [per ref](https://juju.is/docs/sdk/metadata-reference)) from the examples:

```
bundle: kubernetes
applications:
  onos2:
    charm: "../charms/onos.charm"
    scale: 1
    options:
      admin-password: admin
    resources:
      onos-image: onosproject/onos:2.6.0
```
https://github.com/juju/python-libjuju/blob/master/examples/k8s-local-bundle/bundle.yaml


If you replace the first line with `series: kubernetes`, then we get a plan with 3 consecutive `addUnit` changes after an `addCharm` with 0 units, (as opposed to getting an addCharm change with 3 units), which should error, because it's supposed to be container-based (i.e. shouldn't use `addUnit`). Juju cli confirms this:

```sh
$ juju deploy ./addunit-bundle.yaml
Executing changes:
- upload charm /home/caner/work/cderici/python-libjuju/examples/charms/onos.charm for series kubernetes with architecture=amd64
- deploy application onos2 on kubernetes
  added resource onos-image
- add unit onos2/3 to new machine 0
ERROR cannot deploy bundle: cannot add unit for application "onos2": adding units to a container-based model not supported (not supported)
```

@johnsca is this what was going on when you filed this (looks like this was a while ago, so if you recall)? It would be significantly easier if I could see the bundle that's used.

**Comment by cderici** [comment] 2021-12-15 18:18
Closing this. Looks like the issue comes from the used bundle.

**Closed by cderici** 2021-12-15 18:18 UTC
