### ISSUE TITLE
python lib for juju 2.9.4 breaks ubuntu juju charm deployment: raise JujuError("resolve charm")

### ISSUE THREAD

**Issue by patriciadomin** [juju/python-libjuju#586] opened 2021-11-18 20:06 UTC
python-libjuju 2.9.4 breaks juju charm deployment called as: 

```python

from juju.controller import Controller 

async def main(argsseries, argsconstraints=None):
    controller = Controller()
    await controller.connect_current()
    try:
        model = await controller.add_model(ModelName)
 
        application = await model.deploy(
            "ubuntu",
            application_name="ubuntu",
            series=argsseries,
            channel="stable",
            constraints=constraints.parse(argsconstraints),
        )
```

This will raise an error:
```
Traceback (most recent call last):
  File "/srv/scalebot/repo/tests/juju-deploy-ubuntu.py", line 25, in main
    application = await model.deploy(
  File "/usr/local/lib/python3.8/dist-packages/juju/model.py", line 1593, in deploy
    res = await self.deploy_types[str(url.schema)].resolve(url, architecture, application_name, channel, series, entity_url)
  File "/usr/local/lib/python3.8/dist-packages/juju/model.py", line 549, in resolve
    charm_url, origin = await self.charm_resolver(url, origin)
  File "/usr/local/lib/python3.8/dist-packages/juju/model.py", line 1692, in _resolve_charm
    raise JujuError("resolve charm")
juju.errors.JujuError: resolve charm
```
downgrading lib to 2.9.3 it works again as previous versions

**Comment by cderici** [comment] 2021-11-18 20:27
Can you also provide the values for the `argseries` and `argconstraints`? 
Because this is actually working for me when I set `argseries='trusty'` and `argconstraints=None`, so I'm currently unable to reproduce this problem.

**Comment by patriciadomin** [comment] 2021-11-19 19:57
@cderici series - all available: xenial, bionic, focal, hirsute. Calling the python script: `juju-deploy-ubuntu.py -s focal -c "tags=$tag arch=$arch"` as it is running on arm64 and amd64 systems

**Comment by cderici** [comment] 2021-11-22 20:23
@patriciadomin I'm sorry I should be more clear. Can you please provide the exact values of `argseries` and `argconstraints` that broke this and produced this particular error you wrote in the description? I tried again with `xenial` for the series as well as `amd64` for the arch in constraints and it's resolving and deploying the charm no problem.

I suspect it has something to do with the constraints, but to confirm that I need to be able to reproduce your error, for which I need the exact parameters you used for `deploy` when this happened. I see that you use `tags` and `arch` for the constratints, but I don't have the values of your `$tag` and `$arch` parameters. So if you can provide their values, then I'll be able to make the exact call you made in `juju-deploy-ubuntu.py -s focal -c "tags=$tag arch=$arch"` and hopefully reproduce the exact same error. From there I can start diagnosing what's going on and hopefully fixing the issue. Thanks!

**Comment by patriciadomin** [comment] 2021-11-24 13:50
@cderici sorry too, I should have mentioned this juju instance has a `maas` cloud type - it selects a server on our MAAS pool for deploying an ubuntu juju charm on tagged machines. 4 examples on amd64 and arm64: 

`juju-deploy-ubuntu.py -s bionic -c "tags=certified,owner-hwe,model-d05 arch=arm64"`
`juju-deploy-ubuntu.py -s focal -c "tags=certified,owner-hwe,model-d05 arch=arm64"`
`juju-deploy-ubuntu.py -s bionic -c "tags=certified,owner-hwe,model-dgx2 arch=amd64"`
`juju-deploy-ubuntu.py -s focal -c "tags=certified,owner-hwe,model-dgx2 arch=amd64"`

**Comment by SimonRichardson** [comment] 2021-11-24 14:05
I'm assuming `ModelName` from your original script is different for every deploy? 

You should have a different name for the application if you're deploying the same charm twice. If you want to add a different series to the same charm, you have to call `set-series` then do `add-unit`.

```
juju-deploy-ubuntu.py -s bionic -c "tags=certified,owner-hwe,model-d05 arch=arm64"
juju-deploy-ubuntu.py -s focal -c "tags=certified,owner-hwe,model-d05 arch=arm64"
```

**Comment by SimonRichardson** [comment] 2021-11-24 14:11
@patriciadomin can you prefix your charm name with `cs:`, I'm guessing your version of Juju is less than 2.9?

Becomes:
```
model.deploy(
            "cs:ubuntu",
```

See "Fully qualified charm URLs" from https://discourse.charmhub.io/t/charmhub/3991

> It is now expected that all CharmStore URLs are fully qualified. Previously you didn’t necessarily have to fully qualify the schema of the charm URL, it was seen as good practice to do so. The change is simple, adding a cs: prefix to your URLs will ensure that it comes from the CharmStore.
>     `mattermost becomes cs:mattermost`

**Comment by patriciadomin** [comment] 2021-11-24 15:11
adding the `juju-deploy-ubuntu.py`: 
```python
#!/usr/bin/python3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
 
import sys
import os
import asyncio
import logging
import argparse
from juju.controller import Controller
from juju import loop
from juju import constraints
from async_timeout import timeout
from asyncio import CancelledError, TimeoutError
import ScaleBot.util
 
ModelName = ScaleBot.util.build_tag_to_model_name(os.environ["BUILD_TAG"])
 
 
async def main(argsseries, argsconstraints=None):
    controller = Controller()
    await controller.connect_current()
 
    try:
        model = await controller.add_model(ModelName)
 
        application = await model.deploy(
            "ubuntu",
            application_name="ubuntu",
            series=argsseries,
            channel="stable",
            constraints=constraints.parse(argsconstraints),
        )
 
        logging.info("Waiting for active")
        with timeout(2400):
            await model.block_until(
                lambda: all(
                    unit.workload_status == "active" for unit in application.units
                )
            )
 
        logging.info("Verifying that we can SSH into the created model")
        hostname = await asyncio.create_subprocess_exec(
            "juju",
            "ssh",
            "-m",
            ModelName,
            "ubuntu/0",
            "hostname",
            stdout=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await hostname.communicate()
        hostname_str = stdout.decode("UTF-8")
        hostname_str = hostname_str.rstrip("\n")
        logging.info("HOSTNAME: {}".format(hostname_str))
        logging.info("{} is deployed and ready for further usage.".format(hostname_str))
        logging.info("Disconnecting from controller")
 
        await model.disconnect()
        await controller.disconnect()
 
    except (CancelledError, TimeoutError) as e:
        # Logging used as magic text to detect machine unavailability
        logging.exception("Job cancelled. Maybe no target machines are available.")
        logging.info(e)
        model_uuid = model.info.uuid
        logging.info("Disconnecting the corresponding model {} ...".format(model_uuid))
        await model.disconnect()
        logging.info("Destroying the corresponding model...")
        await controller.destroy_model(model_uuid)
        logging.info("Disconnecting from controller...")
        await controller.disconnect()
        sys.exit("Stop running Checkbox")
 
    except Exception as e:
        logging.exception(
            "Test failed! Model {} may not be cleaned up".format(ModelName)
        )
        logging.info(e)
        model_uuid = model.info.uuid
        logging.info("Disconnecting the corresponding model {} ...".format(model_uuid))
        await model.disconnect()
        logging.info("Destroying the corresponding model...")
        await controller.destroy_model(model_uuid)
        logging.info("Disconnecting from controller...")
        await controller.disconnect()
        sys.exit(-1)
 
 
parser = argparse.ArgumentParser()
 
parser.add_argument(
    "-s",
    "--series",
    help="Machine Series, Example:\
                    xenial, bionic, focal, etc",
    required=True,
)
parser.add_argument(
    "-c",
    "--constraints",
    help="string of space separated key values, Example: "
    " juju deploy foo --constraints 'tags=owner=hwe arch=arm64 mem=4G cores=2'. "
    "All constraints supported by Juju can be used. Tags are a comma-delimited "
    "strings assigned to a specific machine and can be positive, denoting an "
    "attribute of the machine, or negative (prefixed with '^'), to denote "
    "something that the machine does not have",
    default=None,
    required=False,
)
args = parser.parse_args()
# Change this do logging.DEBUG for more verbose output
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
loop.run(main(args.series, args.constraints))

**Comment by patriciadomin** [comment] 2021-11-24 15:13
> I'm assuming `ModelName` from your original script is different for every deploy?
> 
> You should have a different name for the application if you're deploying the same charm twice. If you want to add a different series to the same charm, you have to call `set-series` then do `add-unit`.
> 
> ```
> juju-deploy-ubuntu.py -s bionic -c "tags=certified,owner-hwe,model-d05 arch=arm64"
> juju-deploy-ubuntu.py -s focal -c "tags=certified,owner-hwe,model-d05 arch=arm64"
> ```

Yes `ModelName` is different for every deployment.

**Comment by SimonRichardson** [comment] 2021-11-25 07:26
@patriciadomin what version of juju are you using?

**Comment by patriciadomin** [comment] 2021-11-25 20:44
@SimonRichardson yes juju version was 2.8.13. I've tried adding `cs:ubuntu` instead of `ubuntu` and got a new error: 
```
Traceback (most recent call last):
  File "/srv/scalebot/repo/tests/juju-deploy-ubuntu.py", line 25, in main
    application = await model.deploy(
  File "/usr/local/lib/python3.8/dist-packages/juju/model.py", line 1622, in deploy
    charm_origin = add_charm_res.charm_origin
AttributeError: 'NoneType' object has no attribute 'charm_origin'
```

I've upgraded juju (from 2.8.13) to -> 2.9.19** and was able to deploy ubuntu charm either ways: with `cs:ubuntu` and also only `ubuntu` although the last one gives me this message: `INFO: Deploying ch:amd64/focal/ubuntu-19` (and I'm deploying an arm64 server) and it shows an error message with `juju status`, but it is able to deploy successfully:
``` 
~$ juju status
ERROR failed to parse charm: cannot parse URL "ch:amd64/focal/ubuntu-19": schema "ch" not valid
Model                                       Controller  Cloud/Region      Version  SLA          Timestamp
scalebot-jenkins-kernel-soc-hi1620-focal-8  jenkins     scalebot/default  2.9.19   unsupported  19:48:41Z

App     Version  Status  Scale  Charm  Store  Rev  OS      Notes
ubuntu  20.04    active      1                  0  ubuntu  
```

**I saw juju version 2.9.19 was released 2 days ago, not sure if something has changed and it does not require `cs`.
Let me know if I can provide any other info or test.

**Comment by SimonRichardson** [comment] 2021-11-30 15:23
@patriciadomin you have to provide a deploy time constraint to use arm64. It's in the Juju release notes.

**Closed** 2021-12-06 20:52 UTC

**Comment by SimonRichardson** [comment] 2021-12-06 20:54
Closing this, as we fixed the issue around the charm origin raising an error. The `ResolveCharm` issue is a Juju bug when a method/facade isn't available. We should aim to improve that there, I'll make others aware of that issue.
