### ISSUE TITLE
Error creating models

### ISSUE THREAD

**Issue by davigar15** [juju/python-libjuju#680] opened 2022-05-26 13:32 UTC
### How to reproduce it

Libjuju version: Installed from master (latest commit 9281e4362a1beacd1b666d4ec9354b2d13611346)
Juju version: 2.9.29
Microk8s version: v1.23.6

#### Create a VM with Multipass

```shell
multipass launch -m 8G -d 50G -c 4 -n test
multipass exec test bash
sudo snap install juju --classic
sudo snap install microk8s --classic
sudo usermod -a -G microk8s ubuntu
sudo chown -f -R ubuntu ~/.kube
newgrp microk8s
microk8s.status --wait-ready
microk8s.enable storage dns
juju bootstrap microk8s
```

#### Install libjuju

```shell
sudo apt update
sudo apt install python3-pip -y
git clone https://github.com/juju/python-libjuju
cd python-libjuju/
python3 -m pip install -e .
```

#### Execute script

```shell
cat << EOF > test.py
import asyncio
import random

from juju import jasyncio
from juju.controller import Controller


async def main():
    controller = Controller()
    # connect to current controller with current user, per Juju CLI
    await controller.connect()
    start_number = random.randint(0, 10000000)
    num_of_models = 5
    try:
        for model_name in [f"test-{i}" for i in range(start_number, start_number + num_of_models)]:
            print(f"Creating model {model_name}")
            model = await controller.add_model(model_name)
            await model.disconnect()
        for model_name in [f"test-{i}" for i in range(start_number, start_number + num_of_models)]:
            print(f"Destroying model {model_name}")
            await controller.destroy_model(model_name)
    finally:
        await controller.disconnect()


if __name__ == "__main__":
    jasyncio.run(main())
EOF

python3 test.py
```

### Logs

```
$ python3 test.py
Creating model test-4072097
Creating model test-4072098
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kubernetes/stream/ws_client.py", line 548, in portforward_call
    websocket = create_websocket(configuration, url, headers)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kubernetes/stream/ws_client.py", line 478, in create_websocket
    websocket.connect(url, **connect_opt)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/websocket/_core.py", line 244, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/ubuntu/.local/lib/python3.8/site-packages/websocket/_http.py", line 136, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/websocket/_http.py", line 272, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/websocket/_http.py", line 220, in _wrap_sni_socket
    context.load_verify_locations(cafile=cafile, capath=capath)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 27, in <module>
    jasyncio.run(main())
  File "/home/ubuntu/python-libjuju/juju/jasyncio.py", line 118, in run
    raise task.exception()
  File "test.py", line 17, in main
    model = await controller.add_model(model_name)
  File "/home/ubuntu/python-libjuju/juju/controller.py", line 354, in add_model
    await model._connect_direct(**kwargs)
  File "/home/ubuntu/python-libjuju/juju/model.py", line 757, in _connect_direct
    await self._connector.connect(**kwargs)
  File "/home/ubuntu/python-libjuju/juju/client/connector.py", line 74, in connect
    self._connection = await Connection.connect(**kwargs)
  File "/home/ubuntu/python-libjuju/juju/client/connection.py", line 327, in connect
    self.proxy.connect()
  File "/home/ubuntu/python-libjuju/juju/client/proxy/kubernetes/proxy.py", line 51, in connect
    self.port_forwarder = portforward(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kubernetes/stream/stream.py", line 35, in _websocket_request
    return api_method(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 1142, in connect_get_namespaced_pod_portforward
    return self.connect_get_namespaced_pod_portforward_with_http_info(name, namespace, **kwargs)  # noqa: E501
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 1229, in connect_get_namespaced_pod_portforward_with_http_info
    return self.api_client.call_api(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kubernetes/stream/ws_client.py", line 551, in portforward_call
    raise ApiException(status=0, reason=str(e))
kubernetes.client.exceptions.ApiException: (0)
Reason: [Errno 2] No such file or directory
```

**Comment by cderici** [comment] 2022-05-26 22:58
This is not caused by the `add_model`, but it's about the `disconnect` right after creation, which I believe causes a race between the connection close and the `pinger` event (might also be the allwatcher). You can observe it yourself by adding `logging.basicConfig(level='DEBUG')` in the script. The problem is I believe that the disconnect calls the `websockets.close()` and while it's tearing down the connection, the pinger is trying to ping using the same connection. 
The reason that I'm not so sure is that this seems to be working in `lxd` without a problem - though it might also be intermittent.

Anyways your particular issue goes away by either removing the `await model.disconnect()` call (i.e. letting the python runtime + os to tear it down), or not call it directly after. Like so:

```python
async def main():
    controller = Controller()
    # connect to current controller with current user, per Juju CLI
    await controller.connect()
    start_number = random.randint(0, 10000000)
    num_of_models = 5
    models = []
    try:
        for model_name in [f"test-{i}" for i in range(start_number, start_number + num_of_models)]:
            print(f"Creating model {model_name}")
            models.append(await controller.add_model(model_name))
        for m in models:
            await m.disconnect()
        for model_name in [f"test-{i}" for i in range(start_number, start_number + num_of_models)]:
            print(f"Destroying model {model_name}")
            await controller.destroy_model(model_name)
    finally:
        await controller.disconnect()
```

Hope this solves the problem for you. Feel free to let us know if it doesn't.

**Comment by juanmanuel-tirado** [comment] 2022-05-27 08:27
I will close this issue. Please, feel free to reopen if the proposed solution does not work for you.

**Closed by juanmanuel-tirado** 2022-05-27 08:27 UTC
