### ISSUE TITLE
With 2.8.1 Release, pylibjuju could use admin facade to login

### ISSUE THREAD

**Issue by petevg** [juju/python-libjuju#429] opened 2020-07-01 14:18 UTC
Previously, the admin facade has been "hidden," and not included in the list of facades that Juju presents as part of its API.

This behavior will changed in 2.8.1, which would allow pylibjuju to call the admin facade to login, rather than relying on information in the ~/.local/share/juju folder.

**Comment by SimonRichardson** [comment] 2020-08-25 13:56
Duplicate of #436

**Closed by SimonRichardson** 2020-08-25 13:56 UTC
