### ISSUE TITLE
`OSError: [Errno 9] Bad file descriptor` heisen-failure

### ISSUE THREAD

**Issue by sed-i** [juju/python-libjuju#591] opened 2021-11-23 19:39 UTC
Occasionally my integration tests fail early on with:
```
OSError: [Errno 9] Bad file descriptor
```
yet a subsequent test passes smoothly without any changes to anything.

This is a randomly recurring issue observed continuously in the past few months.

[heisen-failure.log](https://github.com/juju/python-libjuju/files/7590596/heisen-failure.log)

**Comment by cderici** [comment] 2021-11-23 20:19
This seems to be related to https://github.com/juju/python-libjuju/pull/580 . We worked on a bunch of issues related to asyncio in there, and we saw that some of the problems were caused by our tests themselves. So I'd start the checking from your test called `test_build_and_deploy_with_alternative_images`.

For example, one of the things that I'd look at, is if the test is manually opening connections then I'd check if it is closing all of them before exiting. Another thing to check would be to see if it's sharing any connections opened somewhere else, if so, then it should be closed somewhere eventually. Another thing to check would be to make sure we're not directly accessing the `ws` object in the test (e.g. `connection.ws.close()`), we found that it causes a bunch of other problems (because asyncio tasks/events are closely tied to the connection itself). Our tests are currently passing consistently after we fixed these sorts of points in our tests.

We also found a bunch of spots internally in `pylibjuju` where we weren't treating the connection object properly, so those seems to be fixed in https://github.com/juju/python-libjuju/pull/580, but it's of course possible that we have missed something in there and that's the cause of your problem.

So to diagnose for both cases, I'd need to see exactly how the `test_build_and_deploy_with_alternative_images` (or any other failing test) is using `pylibjuju`.

**Comment by cderici** [comment] 2021-11-23 20:21
Is it this one https://github.com/canonical/prometheus-operator/blob/ea351276712fd54c45635181eb5296e39274bff1/tests/integration/test_charm.py#L21?

**Comment by sed-i** [comment] 2021-11-23 20:26
> Is it this one https://github.com/canonical/prometheus-operator/blob/ea351276712fd54c45635181eb5296e39274bff1/tests/integration/test_charm.py#L21?

Yes, exactly.

**Comment by sed-i** [comment] 2021-11-23 21:01
Got a tip from @rbarry82:

> Juju is closing the web socket, then asyncio tries to set a property on it. fnctl will not write to a closed FD
> [possibly] a systemd tmpfile timer is removing the LXD socket
> it’s also easy enough to just `systemctl disable systemd-tmpfiles-clean.timer`

**Comment by SimonRichardson** [comment] 2022-02-17 11:46
> websockets.exceptions.ConnectionClosed: code = 0 (unknown), reason = websocket closed

If you look in the logs, it looks like the connection is also being close, but we're not getting a close control frame to tell us why. 

This could actually be the cause of the failure, but it requires Juju to correctly send closed control frames correctly to then see if the problem goes away. See #604

**Closed** 2023-08-12 01:56 UTC
Labels: medium, incomplete
